### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by maahutch** [Escape-Technologies/graphinder#36]
**Describe the bug**
I'm running graphinder via docker against a flask graphql api running on localhost. The application appears to run successfully but generates no report or output. I'm not clear if this result is because there really are no vulnerabilities in my api or because I'm using graphinder incorrectly.  

**To Reproduce**

Ran graphinder docker container first using:

 ` sudo docker run -it  --name graphinder escapetech/graphinder -d 127.0.0.1:5000/graphql` 

and then tried again adding: 
 
` sudo docker run -it --add-host=host.docker.internal:host-gateway --name graphinder escapetech/graphinder -d 127.0.0.1:5000/graphql`

In both cases graphinder returned the following: 

    19:27:34,0756 - INF - graphinder - downloading subfinder...
    19:27:35,0519 - INF - graphinder - extracting subfinder...
    19:27:35,0584 - INF - graphinder - removing subfinder archive...
    19:27:35,0585 - INF - graphinder - starting main routine..
    19:27:35,0585 - INF - graphinder - 1 domains loaded.
    19:27:35,0654 - INF - graphinder - fetching subdomains...
    19:27:40,0664 - INF - graphinder - 127.0.0.1:5000 - found 1 subdomains.
    19:27:40,0664 - INF - graphinder - 0 tasks generated.
    19:27:40,0668 - INF - graphinder - 127.0.0.1:5000 has been scanned completly.
    127.0.0.1:5000 - 0

**Expected behavior**
My concern was about the line `0 tasks generated`. Is there anyway to see what tests graphinder ran? I tried: 
`sudo docker cp graphinder:/graphinder/results.json results.json` as the documentation suggests but received:
`Error: No such container:path: graphinder:/graphinder/results.json` which makes me think I've configured the app incorrectly and nothing actually happened. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS (on wsl)
 - Python Version: 3.9.5 but I'm running graphinder on the docker container
 - Docker Version:  20.10.17, build 100c701
 - Graphinder version: 1.8.0

**Additional context**
I developed a flask graphql api using graphene. I wanted to try and run some kind of fuzzing against it on my local machine before pushing it to deployment. Is graphinder the right tool for this?

**Comment by c3b5aw** [comment]
Hello @maahutch,

It's not a bug as there is no result.
Graphinder scan urls for graphql endpoints using subdomain enumeration.
You already know your endpoint and have no domain. (local wont work)

What do you want to achieve exactly ?
