### ISSUE TITLE
in graphinder, change to #!/usr/bin/env python3

### ISSUE THREAD

**Issue by gprime31** [Escape-Technologies/graphinder#44]
After 
git clone https://github.com/Escape-Technologies/graphinder.git
cd Graphinder
./install-dev.sh
and
poetry shell 
do
nano /usr/local/bin/graphinder
and change the 1st line to:
#!/usr/bin/env python3

**Comment by c3b5aw** [comment]
Hello @gprime31,

I am not understanding what you want to change here.

**Comment by gprime31** [comment]
after the git clone and ./inshall-dev.sh is ran when I run poetry shell, then run  graphinder -d example.com I get
bash: /usr/local/bin/graphinder: python: bad interpreter: No such file or directory  
so in order to fix it I did  
nano /usr/local/bin/graphinder
and changed line 1 to #!/usr/bin/env python3 instead of #!python
![2022-08-25_09-53](https://user-images.githubusercontent.com/44535257/186683591-4412ae43-85f8-4458-99a9-05b58a9e4bfd.png)

**Comment by c3b5aw** [comment]
What is your OS?

**Comment by gprime31** [comment]
ubuntu

**Comment by gprime31** [comment]
![2022-08-25_09-56](https://user-images.githubusercontent.com/44535257/186684204-8d4e6c37-c066-4ae7-ab11-b53a78c9146a.png)
but after the change it works now.

**Comment by c3b5aw** [comment]
what does theses commands says

```
whereis python
python -V
```

**Comment by gprime31** [comment]
![2022-08-25_09-57](https://user-images.githubusercontent.com/44535257/186684454-426d9337-d13d-4767-8f06-4d3f03b04bd4.png)

**Comment by gprime31** [comment]
it's python 3.10

**Comment by c3b5aw** [comment]
Alright, I will try to reproduce myself.

For the meantime, you should use PyPi package.

Try with:
```
pip install graphinder
```

Or maybe `python3 -m pip install graphinder`

and run with `graphinder ...`

**Comment by gprime31** [comment]
> ![2022-08-25_09-56](https://user-images.githubusercontent.com/44535257/186684204-8d4e6c37-c066-4ae7-ab11-b53a78c9146a.png) but after the change it works now.

like i said after the change it works great now.

**Comment by c3b5aw** [comment]
> > ![2022-08-25_09-56](https://user-images.githubusercontent.com/44535257/186684204-8d4e6c37-c066-4ae7-ab11-b53a78c9146a.png) but after the change it works now.
> 
> like i said after the change it works great now.

Sure, but you should not be supposed to fix poetry internals, this is related to graphinder itself

**Comment by gprime31** [comment]
no it's /usr/local/bin/graphinder
not poetry

**Comment by QuentinN42** [comment]
I think it's broken on your side, the `#!python` shebang must access your python executor :
```
> cat x
#!python

import sys

print(sys.version)
> ./x
3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
```

**Comment by gprime31** [comment]
ok, well it's working now anyway, so i'll close and if anyone else runs into this problem, they will have a reference,
Thanks.
Prime
